### ISSUE TITLE
ELF - Everfree Forest nation blocks "Where was kindness?" national focus

### ISSUE THREAD

**Issue by makson96** [EaW-Team/equestria_dev#1501]
I was playing ELF and while in struggle with Changlings, independent Everfree Forest appeared:
![20200721225225_1](https://user-images.githubusercontent.com/1833284/88106654-1f65db00-cba6-11ea-93f0-0d0c2a81699f.jpg)
Now I am blocked from "Where was kindness?" national focus:
![20200721225250_1](https://user-images.githubusercontent.com/1833284/88106738-3e646d00-cba6-11ea-92a7-0f02670ca117.jpg)
I propose, that this focus should be unlocked if ELF **or** Everfree Forest control Everfree Forest province.

**Comment by makson96** [comment]
Presence of Everfree Forest also blocks Equestria Reclaimed focus.

**Comment by makson96** [comment]
I just found that there is Restoration of Equestria decision, which can be used after the war to solve above issues. So this might not be an issue at all.

**Comment by Yard1** [comment]
Jaspy will add some extra checks regardless, thanks. Will close for now, reopen if it persists to be an issue in the next update.
