### ISSUE TITLE
Austurland - focuses "Import Fighter/Bomber Craft" don't add planes

### ISSUE THREAD

**Issue by makson96** [EaW-Team/equestria_dev#1553]
Hi,
Completing focuses "Import Fighter Craft" and "Import Bomber Craft" as Austurland did not add me any planes. This is probably because no plane technology was researched by me (no pre-War Fighter, no pre_war Bomber). This should probably be addressed by adding those technologies in those focusses.
Best regards,
Tomek

**Comment by Yard1** [comment]
Thanks, fixed in https://github.com/EaW-Team/equestria_dev/commit/b98268d57a2e806e9d9b9c0261f69c6715b1eee5
