### ISSUE TITLE
Longsword - "We will never surrender" crashes game

### ISSUE THREAD

**Issue by makson96** [EaW-Team/equestria_dev#1736]
Hoi IV version 1.11.5 beta
Equestria at War version 1.9.1.7

As a Longsword in event "Order Restored" which should put Abba Povner in charge of the country, when you select "We will never surrender.", the game crashes to the desktop.
![hoi4_1](https://user-images.githubusercontent.com/1833284/147390762-21127f30-a911-4275-a59d-e844b72f6a25.png)

Steps to reproduce:
1. Load attached LNS_2.hoi4.
2. Select first option on the event.
3. Select "We will never surrender." in the next event.

Expected result:
Abba Povner is put in charge of the Longsword.

Actual result:
Game crashes to the desktop
[LNS_2.hoi4.zip](https://github.com/EaW-Team/equestria_dev/files/7776122/LNS_2.hoi4.zip)
.

**Comment by Philetairos** [comment]
retire_character sometimes causes crashes for unclear reasons. Me and scars did find a workaround which I will apply now. Blame Paradox for being incompetent

**Comment by makson96** [comment]
There is no need to blame anyone. People do make mistakes and I have reported this one, so it can be fix. It is great that you are aware of this and have a workaround. I hope it can be implemented soon. Best regards.
