### ISSUE TITLE
Tobuck's harmonic faction does not give the appropiate bonuses

### ISSUE THREAD

**Issue by PonyRoleplayer** [EaW-Team/equestria_dev#1865]
Steps to reproduce:

- Play as tobuck
- Go the Tricky Thestral path
- Go Harmonic
- Have 4 members in your faction in total
- Complete focuses with the ifs

Result:

You get the minimum bonuses for each focus, despite the fact that you have four members in your faction.

Observations:
I tag-switched to the other countries, and they didn't seem to have any decision to take. The focuses mention some decisions, maybe that's the problem?

Example with construction speed:
![Image 1](https://user-images.githubusercontent.com/110875238/183552093-31ed2a84-bd58-4faa-a415-0df444f2c4b0.png)
![Image 2](https://user-images.githubusercontent.com/110875238/183552107-72ed6d96-4797-4cc1-90bf-5f48467adb9b.png)
![Image 3](https://user-images.githubusercontent.com/110875238/183552115-0c4aa82e-0a33-447d-9049-f1b78c2bf108.png)

**Comment by Philetairos** [comment]
Please use #bugreports channel on the discord for reporting issues

**Comment by Yard1** [comment]
Should be fixed now
