### ISSUE TITLE
[Ascendancy] Game crash on 12 May 1014

### ISSUE THREAD

**Issue by makson96** [EaW-Team/equestria_dev#1871]
This issue is present with my Ascendancy game. Every time I load my savegame, the game crashes at 12 May 1014.

Configuration:
OS: Debian 11
Hoi4: 1.11.12
Equestria at War: 2.0.0.2

Steps to reproduce:
1. Extract and load attached CTH_4.hoi4
2. Unpause till 12 May 1014 (1 day)

Expected results:
Game continues.

Actual Result:
Game crashes to the desktop

[CTH_4.hoi4.zip](https://github.com/EaW-Team/equestria_dev/files/9354840/CTH_4.hoi4.zip)

**Comment by Yard1** [comment]
Couldn't reproduce with the latest dev version, which means this was most likely fixed!

**Comment by makson96** [comment]
Ok. I figured it out. If I use console to tag to ZAR it will finish focus "Master of the Desert" in 12 May. Then "The Heir-Apparent" event happen. When I click "The Agueliid is dead, long live the Aguellid", the game crash.
Good to know it will be fixed in upcoming update.
Best regards,
