### ISSUE TITLE
Game crashes to desktop after selecting a country on macOS

### ISSUE THREAD

**Issue by VektorPixel** [EaW-Team/equestria_dev#1896]
Hello,

around the update to version 2.0, the problem started that right after selecting a country ("Select Country" button) the game crashed back to the desktop.

As far as I know, this problem only occurs on machines running macOS.
(Tested with macOS 12 and the new 13).

It also doesn't matter if DLCs are active or not.

Game version is: Avalanche v1.12.5.b273 (8eb3) build time: Oct 27 2022 14:09:42
Attached are the log files of my system and the last crash.

What I find interesting is that in the meta.yml the LastRead was "set_controller (1)".
Since the crash happens before the map is displayed, there seems to be a problem with the world map on macOS. However, this is merely a guess.

[system.log](https://github.com/EaW-Team/equestria_dev/files/9942065/system.log)
[error.log](https://github.com/EaW-Team/equestria_dev/files/9942067/error.log)
[code_revisions.log](https://github.com/EaW-Team/equestria_dev/files/9942068/code_revisions.log)
[exception.txt](https://github.com/EaW-Team/equestria_dev/files/9942069/exception.txt)
[gameplaysettings.txt](https://github.com/EaW-Team/equestria_dev/files/9942070/gameplaysettings.txt)
[pdx_settings.txt](https://github.com/EaW-Team/equestria_dev/files/9942072/pdx_settings.txt)
[settings.txt](https://github.com/EaW-Team/equestria_dev/files/9942073/settings.txt)
[meta.txt](https://github.com/EaW-Team/equestria_dev/files/9942080/meta.txt)

**Comment by Philetairos** [comment]
This has been a known issue for a while now, it is up to paradox interactive to fix it. Theres nothing we can do, sorry
